<a href="https://colab.research.google.com/github/arman-hossain45/Deep_learning_Neural_network/blob/main/data_set_And_Data_Loader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import Dataset,DataLoader

In [11]:
x,y =make_classification(
    n_samples=10,
    n_features =2,
    n_informative =2,
    n_redundant=0,
    random_state=42
)

In [6]:
class customDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels =labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,indx):
    return self.features[indx],self.labels[indx]

In [13]:
# object create \

dataset = customDataset(x,y)

In [14]:
#len

len(dataset)

10

In [15]:
dataset[2]

(array([-2.8953973 ,  1.97686236]), np.int64(0))

# DAta loader

In [18]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [19]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)


tensor([[-1.1402, -0.8388],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([0, 0])
tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([1, 0])
tensor([[-0.7206, -0.9606],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0, 1])
tensor([[ 1.8997,  0.8344],
        [ 1.7273, -1.1858]], dtype=torch.float64)
tensor([1, 1])
tensor([[ 1.7774,  1.5116],
        [-1.9629, -0.9923]], dtype=torch.float64)
tensor([1, 0])
