<a href="https://colab.research.google.com/github/arman-hossain45/Deep_learning_Neural_network/blob/main/tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
print(torch.__version__)

2.10.0+cu128


In [11]:
if torch.cuda.is_available():
  print("gpu is available")
  print(f"Device name {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")



gpu is available
Device name Tesla T4


# Creating a tensor

In [13]:
a=torch.empty(2,3)
a

tensor([[-5.0882e+35,  4.3157e-41,  7.2952e-28],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [14]:
type(a)

torch.Tensor

In [15]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
torch.rand(2,3)

tensor([[0.9801, 0.3656, 0.7519],
        [0.4875, 0.5470, 0.5761]])

In [29]:
torch.manual_seed(100)# same number a asbe bar bar change hobe na
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [30]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
torch.eye(5)#identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
torch.arange(0,10,1)#range and step

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Tensor Shape

In [35]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
x.shape

torch.Size([2, 3])

In [37]:
torch.empty_like(x)

tensor([[219043332140, 188978561117, 223338299483],
        [227633266732, 231928234028, 399431958621]])

In [38]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [39]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [40]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data Types

In [41]:
x.dtype

torch.int64

In [42]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)#amra chai amder value gula int a thakuk

tensor([1, 2, 3, 4], dtype=torch.int32)

In [43]:
x.dtype

torch.int64

# we want it at float

In [45]:
x=x.to(torch.float32)
x.dtype

torch.float32

# Mathematical operation

In [46]:
x=torch.tensor([[1,2,3],[3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [47]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [48]:
x-2

tensor([[-1,  0,  1],
        [ 1,  2,  3]])

In [49]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [1.5000, 2.0000, 2.5000]])

In [50]:
# floor value

x=x*100

In [52]:
x

tensor([[100, 200, 300],
        [300, 400, 500]])

In [51]:
x//3

tensor([[ 33,  66, 100],
        [100, 133, 166]])

In [53]:
x**2

tensor([[ 10000,  40000,  90000],
        [ 90000, 160000, 250000]])

In [54]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

# Element wise operation

In [55]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [56]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [57]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [58]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [59]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [60]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [62]:
c=torch.tensor([-1,-2,-3,-4])
c

tensor([-1, -2, -3, -4])

In [63]:
# we want to see the absoulate value
torch.abs(c)

tensor([1, 2, 3, 4])

In [64]:
c=torch.tensor([1,2,3,4])

In [65]:
torch.neg(c)

tensor([-1, -2, -3, -4])

In [66]:
d=torch.tensor([1.1,2.3,4.5,5.6,7.8])
d

tensor([1.1000, 2.3000, 4.5000, 5.6000, 7.8000])

In [67]:
torch.round(d)

tensor([1., 2., 4., 6., 8.])

In [68]:
torch.ceil(d)

tensor([2., 3., 5., 6., 8.])

In [69]:
torch.floor(d)

tensor([1., 2., 4., 5., 7.])

In [70]:
k=torch.tensor([100,200,299,800])

In [72]:
torch.clamp(k,min=1,max=2)# clamming muloto nirdirstho range ar modde niye ase value gula ke

tensor([2, 2, 2, 2])

# Reduction Operation

In [73]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [74]:
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [75]:
torch.sum(e)

tensor(27.)

In [77]:
torch.sum(e,dim=0)#row wise sum

tensor([9., 9., 9.])

In [ ]:
torch.sum(e,dim=1)#column wise sum

In [76]:
torch.mean(e)

tensor(4.5000)

In [78]:
torch.median(e)

tensor(1.)

In [79]:
torch.max(e)

tensor(9.)

In [80]:
torch.min(e)

tensor(0.)

In [81]:
torch.prod(e)

tensor(0.)

In [82]:
torch.std(e)

tensor(4.5935)

In [83]:
torch.var(e)

tensor(21.1000)

In [84]:
# argmax and argmin
torch.argmax(e)# sob cheye boro number ar index

tensor(2)

In [86]:
torch.argmin(e)# sob cheye choto number ar index dekhabe

tensor(0)

# Matrix operation

In [97]:
f = torch.randint(size=(2,3),low=0,high=10)

In [98]:
f

tensor([[8, 3, 3],
        [5, 0, 6]])

In [99]:
g = torch.randint(size=(3,2),low=0,high=10)

In [100]:
g

tensor([[4, 0],
        [8, 4],
        [7, 2]])

In [101]:
#we know that when we multify a matrix its row and column must be calculate
torch.matmul(f,g)

tensor([[77, 18],
        [62, 12]])

In [102]:
# dot product

vector1 = torch.tensor([1,2])
vector2= torch.tensor([3,4])

In [104]:
torch.dot(vector1,vector2)

tensor(11)

In [105]:
f

tensor([[8, 3, 3],
        [5, 0, 6]])

In [107]:
f.shape

torch.Size([2, 3])

In [106]:
# transpose matrix

torch.transpose(f,0,1)

tensor([[8, 5],
        [3, 0],
        [3, 6]])

In [109]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [110]:
torch.det(h)# detemination

tensor(142.)

In [111]:
torch.inverse(h)

tensor([[ 0.0563, -0.2254,  0.4366],
        [ 0.1479, -0.0915,  0.0211],
        [-0.0704,  0.2817, -0.2958]])

# comparision operation

In [112]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

In [113]:
i

tensor([[2, 7, 1],
        [1, 5, 4]])

In [114]:
j

tensor([[4, 1, 1],
        [2, 4, 7]])

In [115]:
i>j

tensor([[False,  True, False],
        [False,  True, False]])

In [116]:
i<j

tensor([[ True, False, False],
        [ True, False,  True]])

In [117]:
i==j

tensor([[False, False,  True],
        [False, False, False]])

In [118]:
# not equal to

i!=j

tensor([[ True,  True, False],
        [ True,  True,  True]])

# special fuuction

In [125]:
p=torch.tensor([0.001,20,30])
p

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

In [120]:
torch.log(p)

tensor([2.3026, 2.9957, 3.4012])

In [121]:
# exponentdial

torch.exp(p)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [122]:
torch.sqrt(p)

tensor([3.1623, 4.4721, 5.4772])

In [123]:
torch.sigmoid(p)

tensor([1.0000, 1.0000, 1.0000])

In [126]:
#softmax

torch.softmax(p,dim=0)

tensor([9.3666e-14, 4.5398e-05, 9.9995e-01])

In [127]:
# Relu
torch.relu(p)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

# Inplace operation

In [129]:
l=torch.tensor([1,2,3])
l

tensor([1, 2, 3])

In [132]:
b=l+5
b

tensor([6, 7, 8])

In [133]:
m=torch.rand(2,3)
n =torch.rand(2,3)

In [137]:
m

tensor([[1.3114, 0.9096, 1.0504],
        [1.3501, 1.0769, 0.1227]])

In [135]:
n

tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [138]:
m.add_(n)# amara aikhan a m a n ar man jog kore m a rekhe diyesi and inpalce true koresi jar karone amader m ar man change hoye gese

tensor([[2.2271, 1.2174, 1.6773],
        [2.1778, 1.7362, 0.2114]])

In [139]:
torch.relu_(m)

tensor([[2.2271, 1.2174, 1.6773],
        [2.1778, 1.7362, 0.2114]])

In [140]:
m.relu_()

tensor([[2.2271, 1.2174, 1.6773],
        [2.1778, 1.7362, 0.2114]])

#  Coping a tesor

In [158]:
a=torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [154]:
b=a

In [155]:
b[2]=30

In [150]:
b

tensor([ 1,  2, 30,  4,  5])

In [156]:
a#kintu amra amon chai na a chage hoye gese totaly but we dont want this

tensor([ 1,  2, 30,  4,  5])

# Clone

In [161]:
x=torch.tensor([1,2,3,4,5])

In [162]:
# clone
y=x.clone()# x amra copy korlam y te
y


tensor([1, 2, 3, 4, 5])

In [163]:
id(x)

132274569687792

In [164]:
id(y)

132274569496128